// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBanwKLQx2dbKr1oS-e-0XoA42MtFpcLPs',
    appId: '1:206835160953:web:84e915ba823c8a0b83c1a8',
    messagingSenderId: '206835160953',
    projectId: 'chat-app-b1d92',
    authDomain: 'chat-app-b1d92.firebaseapp.com',
    storageBucket: 'chat-app-b1d92.appspot.com',
    measurementId: 'G-DNBS9HLPXL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCHDEuOnJxFk7YRQjGLYXaTDBYYmBF43k',
    appId: '1:206835160953:android:314da5784a40c0e083c1a8',
    messagingSenderId: '206835160953',
    projectId: 'chat-app-b1d92',
    storageBucket: 'chat-app-b1d92.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrBbtr8qOO3cvQXa0Xg3AcFLd21peUU-k',
    appId: '1:206835160953:ios:81e2a210580abe3083c1a8',
    messagingSenderId: '206835160953',
    projectId: 'chat-app-b1d92',
    storageBucket: 'chat-app-b1d92.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCrBbtr8qOO3cvQXa0Xg3AcFLd21peUU-k',
    appId: '1:206835160953:ios:a653b5af911afe3283c1a8',
    messagingSenderId: '206835160953',
    projectId: 'chat-app-b1d92',
    storageBucket: 'chat-app-b1d92.appspot.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
